### ISSUE TITLE
HTTP Server

### ISSUE THREAD

**Issue by MDE186** [gnosygnu/xowa#28]
Not an issue but a request.

I know you can already set the startup tab in the options menu, but if you enter localhost:8080 it will take you to the main page and not "http://localhost:8080/en.wikipedia.org/"

Would it be possible to implement the option that the HTTP Server uses the same startup tab setup.

Thanks

**Comment by gnosygnu** [comment]
Hey! Thanks for opening the issue.

Unfortunately, this was a bug in XOWA. There is a command-line argument for specifying the home page for the http server. For example "--http_server_home en.wikipedia.org" would open up to your "http://localhost:8080/en.wikipedia.org/"

Fortunately, this was fixed in tonight's v2.10.2 release. :)

I'm going to close the ticket for now, but let me know if you run into any issues. Thanks!

**Comment by MDE186** [comment]
hey,

Thanks for having a look, but unfortunately the issue is still present. if I navigate to localhost:8282 it still goes too the main page.

thanks.

**Comment by gnosygnu** [comment]
Thanks for the quick follow-up. I tried now but it still does work. Here's what I did:

* Downloaded the latest windows 32-bit release: https://github.com/gnosygnu/xowa/releases/tag/v2.10.2.1
* Launched XOWA in a command line with the following: java -jar xowa_windows.jar --app_mode http_server --http_server_port 8282 --http_server_home en.wikipedia.org
* Navigated to "http://localhost:8282" in Firefox. The main page for en.wikipedia.org loaded. You can sort of tell from the console output below (it loaded images for en.wikipedia.org)

Can you let me know what command-line you're using, as well as OS, browser, and command-line output?

Thanks!

```
D:\xowa>java -jar xowa_windows.jar --app_mode http_server --http_server_port 8282 --http_server_home en.wikipedia.org
XOWA: the XOWA Offline Wiki Application
Copyright (c) 2012 gnosygnu@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

--------------------------------------------------------------------------------

version: 2.10.2.1; build date: 2015-10-12 04:51

arguments:
  [0] = '--app_mode'
  [1] = 'http_server'
  [2] = '--http_server_port'
  [3] = '8282'
  [4] = '--http_server_home'
  [5] = 'en.wikipedia.org'

HTTP Server started: Navigate to http://localhost:8282
localhost:8282|GET|/
localhost:8282|GET|/fsys/user/anonymous/wiki/en.wikipedia.org/html/xowa_common.css
localhost:8282|GET|/fsys/user/anonymous/wiki/en.wikipedia.org/html/xowa_wiki.css
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/popups/popups.css
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/core/core.css
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/search-suggest/search-suggest.css
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/core/core.js
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/core/DOMContentLoaded.js
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/core/exec.js
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/search-suggest/search-suggest.js
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/find/xowa_find_html.css
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/find/xowa_find_html.js
localhost:8282|GET|/fsys/bin/any/xowa/file/app.window/app_icon.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/3/e/8/2/Aphonopelma_behlei01.jpg/120px.jpg
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/3/d/9/e/%E5%9B%BD%E5%AE%B6%E6%B8%B8%E6%B3%B3%E4%B8%AD%E5%BF%83%E5%A4%9C%E6%99%AF.jpg/120px.jpg
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/7/6/9/b/Ascension_de_Madame_Garnerin%2C_le_28_mars_1802_v2_Lib_of_Congress.jpg/100px.jpg
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/3/d/0/c/Mediawiki-logo.png/35px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/b/c/a/1/Meta-logo-35px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/9/d/e/b/Commons-logo-31px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/7/f/b/3/Wikibooks-logo-35px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/f/f/4/3/Wikidata-logo.svg/47px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/6/0/f/9/Wikinews-logo-51px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/4/6/0/1/Wikiquote-logo-51px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/f/b/b/f/Wikisource-logo.png/35px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/b/f/5/8/Wikispecies-logo-35px.png
localhost:8282|GET|/fsys/bin/any/xowa/html/res/lib/jquery/jquery-1.11.3.min.js
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/xowa/popups/popups.js
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/e/3/e/7/Wikiversity-logo-41px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/orig/f/2/1/d/Wiktionary-logo-51px.png
localhost:8282|GET|/fsys/file/commons.wikimedia.org/thumb/d/d/0/0/Wikivoyage-Logo-v3-icon.svg/35px.png
localhost:8282|GET|/fsys/bin/any/xowa/file/app.general/twisty_right.png
localhost:8282|GET|/fsys/user/anonymous/wiki/en.wikipedia.org/html/logo.png
localhost:8282|GET|/fsys/bin/any/xowa/html/res/src/gadgets/navframe/mediawiki.gadget.navframe.js
```

**Comment by MDE186** [comment]
Hey.

Seems there was an issue my side. Sorry. Everything works.

Thanks :)

**Comment by gnosygnu** [comment]
No worries! Glad to hear it's working. Thanks again for the report.
