### ISSUE TITLE
Script error: =Module:wikipedia:49 The Wikimedia language code "goh" is not valid.

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#388]
This comes from the page en.wiktionary.org/wiki/Beiara
It does not occur on mediawiki (a little box on the right appears instead)

I think that this is 'controlled' by the CldrNamesEn.json file
That is, there is a line in that file

    , "goh":"Old High German" 
However no language file exists (neither json nor gfs)
I think that (somehow)  this language exists in name with a fall back to english for all other things

Line 48 of Module:Wikipedia is

    	local wmlang = require("Module:wikimedia languages").getByCodeWithFallback(args["lang"]) or error("The Wikimedia language code \"" .. args["lang"] .. "\" is not valid.")

and line 102

    wmlang:getCanonicalName() .. " [[Wikipedia]] has " .. linktype .. " on:" ..
I infer from this that for this example lang=goh, wmlang:getCanonicalName() is 'Old High German'

In enwiktionary 2019-03-01 there are 6 examples, 4 different languages
'kcg', 'bra', 'goh' and 'umu'

To add further confusion, 'umu' cannot be found in CldrNamesEn.json, but it does exist in mediawiki-extensions-cldr/LocalNames/LocalNamesEn.php
(so is this another list that need to be included)
This is probably a a minor point

**Comment by gnosygnu** [comment]
Thanks for the breakdown. Let me look at it sometime this weekend. I looked at the CLDR stuff several weeks back so the details are relatively fresh in my mind. If I don't make headway, I'll update the issue details and reclassify the schedule

**Comment by gnosygnu** [comment]
Slowly going through the old backlog.

* Resolved 'goh' and CldrNames with the commit above. 
* 'umu' and LocalNames will take longer. I need to add some support for adding the LocalNames data as well as loading them

**Comment by desb42** [comment]
Just thought I would check this issue and have noticed that my version seems to work but the latest xowa-gui seems to contain the above error
Not sure what is happening

**Comment by gnosygnu** [comment]
Sorry, for late follow-up. Tried again today and still no error for me. See log excerpt below.

I know it's pretty straightforward, but can you try again? See steps below. Also, for what it's worth, I'm using 2019-07 enwikt

Thanks!

---

#### Log
```
20190729_010507.361 page_load: loaded wikitext; page=Beiara wikitext_len=542
20190729_010507.385 jtidy.init; elapsed=0
20190729_010507.465 page.async: url=en.wiktionary.org/wiki/Beiara
20190729_010507.466 redlink.redlink_bgn: page=Beiara total_links=9
20190729_010507.531 redlink.redlink_end: redlinks_run=1
```

---

#### Steps
*  Launch XOWA gui
* Go to en.wiktionary.org/wiki/Beiara
  * -> No Script error
* Go to home/wiki/Special:XowaSystemData?type=log_session
  * -> No error in log

**Comment by desb42** [comment]
curioser and curioser, I still get the error
![beiara_release](https://user-images.githubusercontent.com/861631/62029710-4419b380-b1db-11e9-85d1-2d477e70f87a.jpg)

Using the release version (v4.6.2.1907) on dump 2019-03-01, the logs are

    20190729_065910.010 page.load: url=en.wiktionary.org/wiki/Beiara
    20190729_065911.488 page_load: loaded html; page=Beiara html_len=4279
    20190729_065912.526 page.async: url=en.wiktionary.org/wiki/Beiara
    20190729_065912.527 redlink.redlink_bgn: page=Beiara total_links=8
    20190729_065913.275 redlink.redlink_end: redlinks_run=1
Using a fresh build (having resolved #512) and dump 2019-06-01, the logs are

    20190729_063226.669 page.load: url=en.wiktionary.org/wiki/Beiara
    20190729_063227.787 page_load: loaded html; page=Beiara html_len=4279
    20190729_063229.241 page.async: url=en.wiktionary.org/wiki/Beiara
    20190729_063229.242 redlink.redlink_bgn: page=Beiara total_links=8
    20190729_063230.561 redlink.redlink_end: redlinks_run=1

The page itself has a time stamp of 24 February 2019, at 18:42

A couple of observations
1) the size reported is different (542 versus 4279) [just looking at the wikitext I get 540]
2) total_links is different (9 versus 8)

**Comment by gnosygnu** [comment]
Yeah, your observation is key. 

* My version
20190729_010507.361 page_load: loaded ```wikitext;``` page=Beiara wikitext_len=542
* Your version
20190729_063227.787 page_load: loaded ```html```; page=Beiara html_len=4279

I think you're pulling up the pre-compiled HTML from when the bug existed. 

You can test with the wikitext only version by doing the following:
* Go to ```home/wiki/Special:XowaCfg?grp=xowa.wiki.hdumps```
* Uncheck ```Prefer HTML Databases for Read tab```
* Revisit ```en.wiktionary.org/wiki/Beiara```

If you're still getting the error but seeing ```loaded wikitext```, well back to the drawing board

Thanks!

**Comment by desb42** [comment]
oops (again)

Just realised that the page being fetched is the prebuilt html not the one generated from wikitext

In my own testing I usually unset 'Prefer HTML Databases for Read tab'

As a small suggestion, perhap a visual cue (possibly at the top of the page) to indicate html or wikitext generation

**Comment by gnosygnu** [comment]
> As a small suggestion, perhap a visual cue (possibly at the top of the page) to indicate html or wikitext generation

Yeah, embarassingly, I make this mistake quite often.

I think a visual cue is a good idea. I created an issue to track it (#525), but it'll probably be low priority for time being.

Otherwise, I think this issue is done. Thanks!
