### ISSUE TITLE
Sourcefoge Discussion so I am asking here: Run XOWA as portable on windows

### ISSUE THREAD

**Issue by Renegadez** [gnosygnu/xowa#9]
First I want to say I think your software is awesome!
Ok question how to run portable?
I Have XOWA on one computer download extracted it to a folder downloaded wiki files and it is working fine.

I copied that folder to a hard drive brought it to another machine now when i open the folder and click xowa_64.exe the software will not  run nothing happens.

Both system are Win7 64bit and both have up to date java versions what am i doing wrong does it somehow have to be setup again on the new system. I would like to use this on a 128 gig usb stick on different machines. Thank you for your help!

**Comment by gnosygnu** [comment]
> First I want to say I think your software is awesome!

Cool! Thanks for the kind words!!

> Ok question how to run portable?

Yup, it does run portable. Just put the entire XOWA root folder on your flash drive and bring it to another computer. For example, "Z:\xowa" where "Z:" is the drive letter for your flash letter.

> I copied that folder to a hard drive brought it to another machine now when i open the folder and click xowa_64.exe the software will not run nothing happens.

That's odd, but I think it has something to do with that other computer. Try the following on the 2nd computer: 

* Run Z:\xowa\bin\windows_64\xulrunner_v31\xulrunner.exe
    * You should get a message box that starts off with "Mozilla XUL Runner 10.0.10"
    * If it fails with "Can't start because MSVCR100.dll is missing...try reinstalling to fix...", then you will need to install the Visual C++ redistributable. See <s>https://sourceforge.net/p/xowa/discussion/general/thread/cc7d867d/</s> http://www.faqforge.com/windows/fix-the-program-cant-start-because-msvcr100-dll-is-missing-from-your-computer-error-on-windows/
* If xulrunner works, try running "java -jar Z:\xowa\windows_64.jar" from a command prompt. This will show more messages (java is failing; SWT issues)

Hope this helps.

**Comment by Renegadez** [comment]
Yes I have followed the directions in the read me before i posted. I should have said that already. I have the vis C++ 2010 and 2015 installed.  XULrunner did open but did not really do anything I have a screen shot I can send. I ran the JAR command from cmd line and it return this
_________________________
C:\Users\ME>java -Xmx256m -jar C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.
1.1\xowa_windows_64.jar
XOWA: the XOWA Offline Wiki Application
Copyright (c) 2012 gnosygnu@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

--------------------------------------------------------------------------------


version: 2.7.1.1; build date: 2015-07-06 02:51

arguments:
  **** NONE ****
  use --help to show help

Exception in thread "main" org.eclipse.swt.SWTError: Unknown error
        at org.eclipse.swt.internal.mozilla.nsISupports.getMethodIndex(Unknown S
ource)
        at org.eclipse.swt.internal.mozilla.nsIFile.Create(Unknown Source)
        at org.eclipse.swt.browser.AppFileLocProvider.<init>(Unknown Source)
        at org.eclipse.swt.browser.Mozilla.create(Unknown Source)
        at org.eclipse.swt.browser.Browser.<init>(Unknown Source)
        at gplx.gfui.Swt_html.<init>(Unknown Source)
        at gplx.gfui.Swt_kit.New_html(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_itm.Make_html_box(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_mgr.Tabs_new(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_mgr.Tabs_new_init(Unknown Source)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Launch_tab(Unknown Source)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Restore_tab_failover(Unknown So
urce)
        at gplx.xowa.gui.views.Xog_launcher_tabs.Launch(Unknown Source)
        at gplx.xowa.gui.views.Xog_tab_itm_read_mgr.Launch(Unknown Source)
        at gplx.xowa.gui.Xoa_gui_mgr.Run(Unknown Source)
        at gplx.xowa.Xoa_app_boot_mgr.Run_app(Unknown Source)
        at gplx.xowa.Xoa_app_boot_mgr.Run(Unknown Source)
        at gplx.xowa.Xoa_app_.Run(Unknown Source)
        at gplx.xowa.Xowa_main.main(Unknown Source)

**Comment by gnosygnu** [comment]
> Yes I have followed the directions in the read me before i posted. 

Sorry. I had to ask. 2 or 3 users had the same problem without reading the readme.txt. I've been told no one reads the readme. :)

>  XULrunner did open but did not really do anything I have a screen shot I can send.

Cool. No need for the screenshot

>  I ran the JAR command from cmd line and it return this

Interesting. This looks like an SWT / XULRunner issue. This link shows that the getMethodIndex was a known issue at one point in time: https://bugs.eclipse.org/bugs/show_bug.cgi?id=437700 . 

For now, try using XulRunner 24. There's really no big difference between 24 and 31. You'd have to do the following:

* Download Xulrunner 24 from http://wiki.mozilla-x86-64.com/Download . Here's the direct link
http://wiki.mozilla-x86-64.com/images/Xulrunner-24.0.en-US.win64-x86_64.zip
* Unzip xulrunner 24 to C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\bin\windows_64\ .
* Rename the directory to xulrunner_v24. When you're done, you want a file like C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\bin\windows_64\xulrunner_v24\xulrunner.exe .
* Open the file at C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\bin\windows_64\xowa\cfg\xowa_cfg_os.gfs
* Change "xul_runner_path = '~{<>bin_plat_dir<>}xulrunner_v31';" to "xul_runner_path = '~{<>bin_plat_dir<>}xulrunner_v24';"
* Run java -Xmx256m -jar C:\Users\ME\Desktop\xowa_app_windows_64_v2.7

If it still fails, send me the console output again.

If I get more reports about these types of errors, I may downgrade to XulRunner 24. But I'm hoping it's a machine-related issue as it seems to work on one of your boxes but not the other (Incidentally, can you think of any meaningful difference between the two?)

Thanks!

**Comment by Renegadez** [comment]
Strange it gave me the same out error message. The portability of XOWA may be more complicated than can be used for my needs as I would have to configure every machine I used it on with the dependencies it requires. I had hoped it was abit more self contained. But it does work great on a completely configured machine. I am not sure what this home machine could be missing as I just built it not long ago for a plex server. in any case thank you so much for your help!

**Comment by gnosygnu** [comment]
> Strange it gave me the same out error message. 

Ok. Thanks for trying.

I found this link: http://permalink.gmane.org/gmane.comp.ide.eclipse.platform.swt.devel/3341 . Someone else reported a similar issue with SWT a few days ago.

Can you try one other thing? I'd like to see if SWT 4.4 works instead of SWT 4.5
* Download SWT 4.4 from http://download.eclipse.org/eclipse/downloads/drops4 . The direct link is : http://download.eclipse.org/eclipse/downloads/drops4/R-4.4.2-201502041700/download.php?dropFile=swt-4.4.2-win32-win32-x86_64.zip
* Unzip the zip file and move the swt.jar to C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\bin\windows_64\swt\swt.jar . You'll be replacing the existing copy (or rename the old one if you want to fall back to it)
* Run java -Xmx256m -jar C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\xowa_windows_64.jar

> The portability of XOWA may be more complicated than can be used for my needs as I would have to configure every machine I used it on with the dependencies it requires. I had hoped it was abit more self contained.

Honestly, portability shouldn't be an issue. I've stuck it on a flash drive and have personally run it from over a dozen machines. In terms of users, there have only been a handful of issues. The main sticking points are Java runtime (needs to be installed), SWT / XULRunner (as you've seen) and SQLite3 (on Raspberry PI). The rest is platform-agnostic code. It really should be portable.

You can also try XOWA in HTTP Server mode. This would bypass SWT / XULRunner. Here's what you would need to do:

* Launch XOWA with the following command line: java -jar xowa_windows_64.jar --app_mode http_server --http_server_port 8080
* Open your browser and navigate to http://localhost:8080

Let me know if I can help in any way. Thanks.

**Comment by Renegadez** [comment]
Sorry I did not get a chance to try this last night but I will. On another note I downloaded the IMAGE files such as Xowa_enwiki_2015-04-03_wiki_file_core.7z
Xowa_enwiki_2015-04-03_wiki_file_ns-000_part-1.7z
I extracted them to their own folders imges but so of the files are named the same as what is already located in my \wiki\en.wikipedia.org folder. The files are clearly different as they are different sizes do the image files need to be located somewhere else? Thanks RenZ

**Comment by gnosygnu** [comment]
> Sorry I did not get a chance to try this last night but I will.

No problem. Whenever you get a chance.

> On another note I downloaded the IMAGE files such as Xowa_enwiki_2015-04-03_wiki_file_core.7z
Xowa_enwiki_2015-04-03_wiki_file_ns-000_part-1.7z

There should only be one file that should be the same: en.wikipedia.org-file-core.xowa . The file that is on your hard drive should be overwritten by the file from the.7z

The rest should be all "new". They'll have a file name like "en.wikipedia.org-file-ns.000-db.001.xowa"  with either a different "ns.###" (EX: ns.100) or a different "db.###" (EX: db.002)

If there is a duplicate file, can you give an example?

> do the image files need to be located somewhere else? 

Nope. They should go to /xowa/wiki/en.wikipedia.org  where /xowa/ is wherever you installed xowa (like C:\Users\ME\Desktop\xowa_app_windows_64_v2.7.1.1\ above). For example, assuming a C:\xowa, you'd have a file called C:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-file-ns.000-db.001.xowa)

Hope this helps.

**Comment by Renegadez** [comment]
OK i was able to get the files copied correctly in the proper directory thank you

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up.

Any luck with copying SWT 4.4? (https://github.com/gnosygnu/xowa/issues/9#issuecomment-122727489)

**Comment by gnosygnu** [comment]
The XULRunner issue should be fixed in tonight's v2.8.1 release. I'm going to close this ticket for now. If there are any issues, let me know, and I'll reopen. Thanks.

**Comment by Terminatrix** [comment]
Just wanna say thanks! I was hunting the same bug that Renegadez had (```"Unknown error
at org.eclipse.swt.internal.mozilla.nsISupports.getMethodIndex(Unknown Source"```) when trying to use the Browser widget in one of my own SWT projects at least for 2.5 hours now, short before giving up. 

Just found your solution/workaround ("using SWT 4.6M1") on https://www.reddit.com/r/xowa/comments/3dwlx7/release_minor_v273_add_new_bookmarks_page_minor/ctxjiji and: **tadaa**, it works. Finally! Great!

[Platform, just in case someone else stumbles across the same issue: Win 7 64 bit, SWT 4.5, and it also neither worked with XULrunner 24, nor with 31 - I even tried it with a 32 bit JRE + 32 bit XULRunners + 32 bit SWT library]

**Comment by gnosygnu** [comment]
Cool! Thanks for dropping by with the comment.

Yeah, I'm surprised that 4.6 fixed the issue. 4.5 was SWT's milestone release, and this was a pretty big defect.

Glad to hear the approach works on your side. Best of work on your projects!

**Comment by Terminatrix** [comment]
> Glad to hear the approach works on your side. Best of work on your projects!

Thanks! For yours  too ;). Seems you've got an amazing project there with xowa.

@ topic:
Interesting: By chance I switched back to SWT 4.5 and found out it works now ![eek](https://doc.tiki.org/img/smiles/icon_eek.gif).
I *do* still get an error in the log --
```1450553507162	addons.manager	ERROR	startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.setCharPref]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/AddonManager.jsm :: AMI_startup :: line 645"  data: no] Stack trace: AMI_startup()@resource://gre/modules/AddonManager.jsm:645 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2318 < AMC_observe()@resource://gre/components/addonManager.js:55 < <file:unknown>```
-- *but* the Browser starts up normally nonetheless (and definitely with Mozilla working in it, not IE). It seems SWT 4.6M1 has set some parameter either in registry or in a config file, so that now also 4.5 is happy (?). ![gr](http://forum.gleitz.info/images/smilies/gruebel.gif)

[Yes, I really double-checked that it is not accidently still 4.6M1 I'm loading now.]

**Comment by gnosygnu** [comment]
> Thanks! For yours too ;). Seems you've got an amazing project there with xowa.

Hey, thanks!

> Interesting: By chance I switched back to SWT 4.5 and found out it works now

Odd. I don't have a Windows 8 box, but I remember that when I tested it on the loaner box, it always failed on 4.5 and worked on 4.6 (I switched back and forth to confirm)

> I do still get an error in the log -- 1450553507162 addons.manager ERROR startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE)

The error message is mostly harmless and is sort of a known SWT issue. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=437700 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=466391 . I get it on my machine, but have not seen any other side-effects.

> [Yes, I really double-checked that it is not accidently still 4.6M1 I'm loading now.]

Yeah, don't know how to explain it....
